### Read user
GET http://localhost:3000/api/user

### Create user
POST http://localhost:3000/api/user
Content-Type: application/json

### Login
POST http://localhost:3000/api/login
Content-Type: application/json

{
    "username": "abcd",
    "password": "12345"
}

### Test
GET https://rfid-next-kappa.vercel.app/api/user

### Seed
POST https://rfid-next-kappa.vercel.app/api/seed
Content-Type: application/json

###> Seed local
POST http://localhost:3000/api/seed
Content-Type: application/json

